### get all films ###########################################################
GET http://localhost:3000/api/films/



#### get film with id ###
### invalid id
GET http://localhost:3000/api/films/a

### no film with given id
GET http://localhost:3000/api/films/99

### film with given id
GET http://localhost:3000/api/films/{{$randomInt 1 6}} HTTP/1.1


### add new film ###########################################################
### invalid title
POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "",
    "isFavorite": false,
    "watchDate": "",
    "rating": null,
    "userId": 1
}

### invalid userId
POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover",
    "isFavorite": false,
    "watchDate": "",
    "rating": null,
    "userId": "A"
}


### valid params
POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover"
}


### update added film ###########################################################

POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover"
}

### invalid id
PUT http://localhost:3000/api/films/a
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### inexistent id
PUT http://localhost:3000/api/films/66
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}


### valid parameters
PUT http://localhost:3000/api/films/6
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}


### update favorite field of added film ###########################################################

POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover"
}

### invalid id
PUT http://localhost:3000/api/films/a/favorite
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### inexistent id
PUT http://localhost:3000/api/films/66/favorite
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### invalid parameters
PUT http://localhost:3000/api/films/6/favorite
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": 4,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### inexistent parameters
PUT http://localhost:3000/api/films/6/favorite
Content-Type: application/json

{
  "title": "The Hangover 2",
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### valid parameters
PUT http://localhost:3000/api/films/6/favorite
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}


### update rating field of added film ###########################################################

POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover"
}

### invalid id
PUT http://localhost:3000/api/films/a/rating
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### inexistent id
PUT http://localhost:3000/api/films/66/rating
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### invalid parameters
PUT http://localhost:3000/api/films/6/rating
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating":"yes",
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### valid inexistent parameters
PUT http://localhost:3000/api/films/6/rating
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### valid parameters
PUT http://localhost:3000/api/films/6/rating
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 3,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}


### delete added film ###########################################################

PUT http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover"
}

### invalid id
DELETE http://localhost:3000/api/films/a

### inexistent id
DELETE http://localhost:3000/api/films/66


### valid id
DELETE http://localhost:3000/api/films/6

### valid id, film inexistent after delete
DELETE http://localhost:3000/api/films/6

