### get all films ###########################################################
GET http://localhost:3000/api/films/



#### get film with id ###
### invalid id
GET http://localhost:3000/api/films/a

### no film with given id
GET http://localhost:3000/api/films/99

### film with given id
GET http://localhost:3000/api/films/{{$randomInt 1 6}} HTTP/1.1


### add new film ###########################################################
### invalid title
POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "",
    "isFavorite": false,
    "watchDate": "",
    "rating": null,
    "userId": 1
}

### invalid userId
POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover",
    "isFavorite": false,
    "watchDate": "",
    "rating": null,
    "userId": "A"
}


### valid params
POST http://localhost:3000/api/films/
Content-Type: application/json

{
    "title": "The Hangover"
}


### add new film ###########################################################

### invalid id
PUT http://localhost:3000/api/films/a
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}

### valid parameters
PUT http://localhost:3000/api/films/6
Content-Type: application/json

{
  "title": "The Hangover 2",
  "isFavorite": true,
  "rating": 5,
  "watchDate": "{{$datetime 'YYYY-MM-DD'}}",
  "userId": 1
}